# This is a basic workflow to help you get started with Actions

name: PushToFeature
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: featurebranch
   # Jobs to be executed
jobs:
    pmd-run:
        runs-on: ubuntu-latest
        steps:
        # Checkout the source code
            - name: 'Checkout source code'
              uses: actions/checkout@v2

            # Install PMD
            - name: 'Install PMD'
              run: |
                  PMD_VERSION=`cat pmd/pmd-version.txt`
                  wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F$PMD_VERSION/pmd-bin-$PMD_VERSION.zip
                  unzip pmd-bin-$PMD_VERSION.zip -d ~
                  mv ~/pmd-bin-$PMD_VERSION ~/pmd
                  ~/pmd/bin/run.sh pmd --version
            # Run PMD scan
            - name: 'Run PMD scan'
              run: ~/pmd/bin/run.sh pmd -d force-app -R pmd/ruleset.xml -f text
    action-pull-request:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repoistory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run the Action
        uses: devops-infra/action-pull-request@v0.5.3
        with:
          github_token: ${{ secrets.REPO_SCOPED_TOKEN }}
          source_branch: development
          target_branch: master
          title: My pull request
          template: .github/PULL_REQUEST_TEMPLATE.md
          body: "**Automated pull request**"
          reviewer: octocat
          assignee: octocat
          label: enhancement
          milestone: My milestone
          draft: true
          old_string: "<!-- Add your description here -->"
          new_string: "** Automatic pull request**"
          get_diff: true
          ignore_users: "dependabot"
          allow_no_diff: false       
  